#!/usr/bin/env python

'''
Define a property that must have the same value for every class instance (object)

Define a class attribute ”color” with a default value white. I.e., Every Vehicle should be white.

Expected Output:

Color: White, Vehicle name: School Volvo, Speed: 180, Mileage: 12
Color: White, Vehicle name: Audi Q5, Speed: 240, Mileage: 18

'''

class Vehicle:
    # instatce variables
    def __init__(self, name, max_speed, mileage):
        self.name = name
        self.max_speed = max_speed
        self.mileage = mileage
    
    # color is class variable and shared by all Vehicle instances
    color = 'white'

class Bus(Vehicle):
    pass

class Car(Vehicle):
    pass

myBus = Vehicle('School Volvo', 180, 12)

myCar = Vehicle('Audi Q5', 240, 18)

print('Bus is', myBus.color, myBus.__dict__)
print('Car is', myCar.color, myCar.__dict__)