#!/usr/bin/env python

import math
print(math.pi, math.e)

print(math.sin(2 * math.pi / 180))

print(math.sqrt(144), pow(2, 4), 2 ** 4, abs(-45), min(1,4,6,7), max(6,2,7))


print(math.floor(2.567), math.floor(-3), math.trunc(-5.62))


print(round(2.567), round(2.56789,2))

print(math.sqrt(144), 144 ** .5, pow(144, .5))

import random

print(random.random(), random.randint(1, 100))
print(random.choice(['Water', ' Bear', 'Wine']))

from decimal import Decimal
import decimal

print(0.1 + 0.1 + 0.1 - 0.3)                                                    # like what the hell
print(Decimal('0.1') + Decimal('0.1') + Decimal('0.1') - Decimal('0.3'))        # Decimal Chad

f = 0.1
print(f + f + f - 0.30)                                                    
print(Decimal(str(f)) + Decimal(str(f)) + Decimal(str(f)) - Decimal('0.30'))    # Result contains maximum decimal digits automatically

print(Decimal(1) / Decimal(7))
decimal.getcontext().prec = 4                                                   # Set global decimal precision  to 4 
print(Decimal(1) / Decimal(7))
