#!/usr/bin/env python

"""
D = {'food' : 'Spam', 'quantity' : 4, 'color' : 'pink'}
print(D)
print(D['food']) # same as index in sequences but key instead

D['quantity'] += 1
print(D)

# Keys can be created by assignment
D['name'] = 'Mykyta'
print(D)
"""

# Nested

rec = {'name': {'first' : 'Mykyta', 'last' : 'Ponomarenko'},
       'job': ['dev', 'mgr'],
       'age': 28}

print(rec)

print(rec['name']['last']) # 'name' is nested dict. Index it via 'last'
print(rec['job'][-1])      # 'job' is a nest list

rec['job'].append('ceo')   # expand nested list as it is in a separate piece of memory and can grow and shrimk freely
print(rec, "\n")

# Iterate through keys
Ks = list(rec.keys())
for key in Ks:
    print(key, '=>', rec[key])


if not 'f' in rec:         # query the existence of a key
    print('missing')